@startuml

class Bank {
	id: INTEGER [PK][NOT NULL]
	name: TEXT
}

class Account {
	number: TEXT [PK][NOT NULL]
	name: TEXT
	bank_id: INTEGER [FK][NOT NULL]
}

class Transaction {
	'Financial Institut Transaction ID
	FITID: TEXT [PK][NOT NULL]
	date: TEXT
	description: TEXT
	amount: REAL
	account_number: TEXT [FK][NOT NULL]
	category_name: TEXT [FK]
}

class Label {
	name: TEXT [PK]
	category_name: TEXT [FK]
}

class Category {
	name: TEXT [PK]
	description: TEXT
}


Bank "1" -- "0..*" Account
Account "1" -- "0..*" Transaction
Transaction "0..*" -- "1" Category
Label "0..*" -- "1" Category

@enduml